name: recetario_mongodb

services:
  # mongo:
  #   image: mongo:8
  #   container_name: recetario-mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #       - mongo-data:/data/db
  #   restart: unless-stopped

  backend:
    build: ./backend
    container_name: recetario-backend
    # ports:
    #   - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb+srv://carlosorozcok_db_user:kDKmctCQQdQIw7Eg@recetario-cluster.plsosta.mongodb.net/recetario
      - JWT_SECRET=nn&SFFeHKyeIoI6ubo@D)7,txuw0NnlC
      - PORT=3000
    # depends_on:
    #   - mongo
    command: sh -c "if [ ! -d node_modules ] || [ ! -f node_modules/.package-lock.json ]; then npm install; fi && npm start"
    restart: unless-stopped
    networks:
      - caddy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: recetario-frontend
    # Sin ports: Caddy enruta por la red de Docker.
    # Sin volumes: el build se hace dentro de la imagen, no en el host.
    # Sin command: nginx escucha en el puerto 80 por defecto.
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true
    name: caddy-central_default

# volumes:
#   mongo-data:
